services:
  mysql:
    image: mysql:9.1
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nestjsrealworld
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  mysql:
    driver_opts:
      type: tmpfs
      device: tmpfs
